---
title: "Resume"
---

**Sammy Tetrault**

**Fort Collins, CO \| 970-215-0685 \| samanthajoantetrault\@gmail.com \| sammytet\@colostate.edu**

**Education**

**Bachelor of Science, Ecosystem Science & Sustainability \| CSU, Fort Collins, CO**

Expected Graduation Fall 2025, GPA: 4.0

Minor in Applied Environmental Policy

**Associate of General Studies \| Front Range Community College, Fort Collins, CO**

Conferred May 2023, GPA: 4.0

**Professional Experience**

**Research Assistant**

CSU Department of Agricultural Biology, Fort Collins, CO \| June 2024 - Present

-   Prepared research materials and planted 2800 seeds for each of the three trials conducted.

-   Collected and entered plant emergence, height, herbicide injury, and vigor data daily.

-   Harvested the sprout, roots, and soil of individuals with true leaves for biomass measurements.

-   Currently assisting with data sorting and analysis using Microsoft Excel and R.

**Undergraduate Teaching Assistant**

CSU, Fort Collins, CO **\|** January 2024 - May 2024

-   Supported a graduate teaching assistant for a LIFE102 lab section by retrieving lab materials, answering student questions, and facilitating group discussions.

-   Provided demonstrations to students for hands-on activities such as pipetting.

-   Taught a lab at the end of the semester to a group of 20 students.

**Relevant Coursework**

**LIFE320, Ecology**

CSU, Fort Collins, CO \| Spring 2024

-   Learned about fundamental ecological concepts such as nutrient cycling, plant physiology, plant responses to disturbance, biotic & abiotic interactions, and population dynamics.

-   Read several scientific papers and became familiar with salient ecological issues such as the proliferation of Emerald Ash Borers.

**Additional Experience**

**Sales Floor Associate**

Kohl’s, Fort Collins, CO \| April 2022 - April 2024

-   Assisted customers both over the phone and in person by answering questions, recommending brands, processing returns, and resolving customer concerns at the service desk.

-   Operated the register in a fast and efficient manner while ensuring customer satisfaction. 

-   Trained new associates.

-   Fulfilled online orders by picking and packing items from the floor.
